remote_theme: just-the-docs/just-the-docs
title: OIPD Docs
url: https://tyrneh.github.io
baseurl: /options-implied-probability
github_username: tyrneh
repository: tyrneh/options-implied-probability
plugins:
  - jekyll-remote-theme
math: katex
